import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
  <div className="navbar bg-base-100 shadow-sm justify-center fixed top-0">
      <Link className="btn btn-ghost normal-case text-xl" to="/">
        Home
      </Link>
      <Link className="btn btn-ghost normal-case text-xl" to="/about">
        About
      </Link>
      <Link className="btn btn-ghost normal-case text-xl" to="/service">
        Service 
      </Link>
    </div>
  {children}</body>
    </html>
  )
}
